### PR TITLE
added insertAt along with tests

### PR DESCRIPTION
**Pull request by f-deladurantaye**

### CODE REVIEW

**Comment by f-deladurantaye** [comment]
Inspired from the insertAt function of the elm-ordered-dict project. Made sure to avoid duplicate keys in the order field of the record.

**Comment by j-maas** [comment]
Thanks for taking the time to open a pull request!

Could you give a use case where you need this function? I'm trying to understand what problem this function solves.

**Comment by f-deladurantaye** [comment]
I'm using it in a form field where a user can add multiple images at once and reorder them by clicking one of the images to move it to head position.

**Comment by j-maas** [comment]
I hope it's ok that I dig a bit deeper, because for now I still have trouble understanding whether the problem you are solving is best solved using an `OrderedDict`.

For managing the order of images, I probably would have used a list. What advantages does using an ordered dict have?

**Comment by f-deladurantaye** [comment]
Hi Johannes, sorry for the late reply.

In fact, you're probably right. I was doing a remangling of some old code that was sub-optimal. After double checking, it would, in fact, be better to use a list in this case. Thanks for pointing this out!

**Comment by j-maas** [comment]
Thanks for your understanding! Also thanks for opening the PR, I appreciate the effort!

**Pull request closed without merging**
